### PR TITLE
Identify as HTML version 5

### PR DESCRIPTION
**Pull request by b1conrad**

### CODE REVIEW

**Comment by b1conrad** [comment]
I think it is good to have this line at (or near, after opening comments) the top of every HTML file you write. For one thing, it will validate better. For another that gets you up-to-date with where the world is now. Even though it says just `html` this is the tag for HTML version 5. The tags for earlier versions are a lot more complicated and you just don't need them anymore anyway.

**Comment by b1conrad** [comment]
Sure enough! Without this the validator give you this error message:
```
Error: Start tag seen without seeing a doctype first. Expected <!DOCTYPE html>.
```

**Comment by b1conrad** [comment]
To make the HTML validator totally happy, you could also address the warning, as my last change above does:
```
Warning: Consider adding a lang attribute to the html start tag to declare the language of this document.
```

**Comment by palsrme** [comment]
CORRECTIONS ADDED TO MY CODE FROM PULL REQUESTS

**Pull request merged**
